# Generated by Django 5.1 on 2024-11-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='servico_prestado',
        ),
        migrations.RemoveField(
            model_name='servicoprestado',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='servicoprestado',
            name='funcionario',
        ),
    ]
